version: "2.4"
services:

  traefik:
    volumes:
      - .\docker\data\traefik:C:/etc/traefik

  mssql:
    volumes:
      - type: bind
        source: .\docker\data\sql
        target: c:\data

  solr:
    volumes:
      - type: bind
        source: .\docker\data\solr
        target: c:\data

  id:
    volumes:
      - ${SITECORE_LICENSE_FOLDER}:c:\license
    environment:
      SITECORE_LICENSE_LOCATION: c:\license\license.xml

  cm:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xp0-cm:${VERSION:-latest}
    build:
      context: ./docker/build/cm
      args:
        PARENT_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xp0-cm:${SITECORE_VERSION}
        TOOLS_IMAGE: ${TOOLS_IMAGE}
        MANAGEMENT_SERVICES_IMAGE: ${MANAGEMENT_SERVICES_IMAGE}
    volumes:
      - ${SITECORE_LICENSE_FOLDER}:c:\license
      - .\docker\data\cm\logs:c:\inetpub\wwwroot\App_Data\logs
      - .\docker\deploy\cm:c:\deploy
    environment:
      SITECORE_LICENSE_LOCATION: c:\license\license.xml
    entrypoint: powershell.exe -Command "& C:\tools\entrypoints\iis\Development.ps1"

  xconnect:
    volumes:
      - ${SITECORE_LICENSE_FOLDER}:c:\license
    environment:
      SITECORE_LICENSE_LOCATION: c:\license\

  xdbsearchworker:
    volumes:
      - ${SITECORE_LICENSE_FOLDER}:c:\license
    environment:
      SITECORE_LICENSE_LOCATION: c:\license\

  xdbautomationworker:
    volumes:
      - ${SITECORE_LICENSE_FOLDER}:c:\license
    environment:
      SITECORE_LICENSE_LOCATION: c:\license\

  cortexprocessingworker:
    volumes:
      - ${SITECORE_LICENSE_FOLDER}:c:\license
    environment:
      SITECORE_LICENSE_LOCATION: c:\license\